name: continuous
on:
  push:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

env:
  BST: bst --config buildstream.conf --colors --builders 1
jobs:
  build:
    name: generate cache
    runs-on: self-hosted
    timeout-minutes: 46000
    steps:
      - uses: actions/checkout@v1
      - name: start buildstream build
        run: ${BST} build installer/image.bst

  tests:
    needs: build
    runs-on: self-hosted
    name: test installer image
    steps:
      - uses: actions/checkout@v1
      - name: run testcase
        run: |
          ${BST} checkout installer/image.bst checkout --force
          podman run --rm -it -v tests:/tests:Z registry.opensuse.org/devel/openqa/containers/isotovideo:qemu-x86 qemu_no_kvm=1 casedir=/tests iso=checkout/rlxos-"${GITHUB_REF##*/}"-x86_64.iso

  deploy:
    needs: build
    runs-on: self-hosted
    name: deploy system image
    steps:
      - uses: actions/checkout@v1
      - name: checkout image
        run: ${BST} checkout installer/image.bst /storage.rlxos.dev/releases/ --force
  
      - name: export disk image
        run: |
          ${BST} checkout system/image.bst system-image --force
          mv system-image/disk.img.xz /storage.rlxos.dev/releases/rlxos-"${GITHUB_REF##*/}"-x86_64-disk.img.xz

  ostree:
    needs: build
    runs-on: self-hosted
    name: commit ostree

    steps:
      - uses: actions/checkout@v1
      - name: commit ostree
        run: |
          echo "${{ github.event.head_commit.message }}" > commit_body
          BRANCH="${GITHUB_REF##*/}" OSTREE_REPO="/ostree.rlxos.dev" OSTREE_GPG="/gpg.rlxos.dev" make update-ostree